/**
 * src/validation/reporter.ts — Gap analysis report formatter
 *
 * Produces two output formats from a GapReport:
 *   - Markdown: human-readable report with summary table and per-page breakdown
 *   - JSON: machine-readable report matching the GapReport type
 */

import type {
  GapReport,
  PageResult,
  FlowResult,
  RequestResult,
  ConsoleResult,
  ScenarioResult,
  FlowStepResult,
  CheckStatus,
  AssumptionResult,
  DefaultResult,
} from './types.js';

// ---------------------------------------------------------------------------
// JSON output
// ---------------------------------------------------------------------------

/** Serialize a GapReport to a JSON string. */
export function toJson(report: GapReport): string {
  return JSON.stringify(report, null, 2);
}

// ---------------------------------------------------------------------------
// Markdown output
// ---------------------------------------------------------------------------

const STATUS_ICON: Record<CheckStatus, string> = {
  passed: 'PASS',
  failed: 'FAIL',
  untested: 'SKIP',
};

const STATUS_EMOJI: Record<CheckStatus, string> = {
  passed: '✅',
  failed: '❌',
  untested: '⬜',
};

function icon(status: CheckStatus): string {
  return `${STATUS_EMOJI[status]} \`${STATUS_ICON[status]}\``;
}

function pct(n: number): string {
  return `${n}%`;
}

/** Render a GapReport as a Markdown string. */
export function toMarkdown(report: GapReport): string {
  const lines: string[] = [];

  // Header
  lines.push(`# Gap Analysis Report: ${report.spec.name}`);
  lines.push('');
  if (report.spec.description) {
    lines.push(`> ${report.spec.description}`);
    lines.push('');
  }

  // Metadata table
  lines.push('## Metadata');
  lines.push('');
  lines.push('| Field | Value |');
  lines.push('|-------|-------|');
  lines.push(`| Spec version | \`${report.spec.version}\` |`);
  lines.push(`| Capture directory | \`${report.capture.directory}\` |`);
  lines.push(`| Capture timestamp | ${report.capture.timestamp} |`);
  lines.push(`| Target URL | ${report.capture.targetUrl || '(unknown)'} |`);
  lines.push(`| Total requests captured | ${report.capture.totalRequests} |`);
  lines.push('');

  // Summary table
  lines.push('## Summary');
  lines.push('');
  lines.push('| Status | Count |');
  lines.push('|--------|-------|');
  lines.push(`| ${STATUS_EMOJI.passed} Passed | ${report.summary.passed} |`);
  lines.push(`| ${STATUS_EMOJI.failed} Failed | ${report.summary.failed} |`);
  lines.push(`| ${STATUS_EMOJI.untested} Untested / Skipped | ${report.summary.untested} |`);
  lines.push(`| **Total** | **${report.summary.total}** |`);
  lines.push(`| **Coverage** | **${pct(report.summary.coverage)}** |`);
  lines.push('');

  // Confidence breakdown
  const allResults = collectAllResults(report);
  const confidenceCounts: Record<string, number> = { observed: 0, inferred: 0, reviewed: 0 };
  let hasConfidence = false;
  for (const r of allResults) {
    if (r.confidence) {
      confidenceCounts[r.confidence] = (confidenceCounts[r.confidence] ?? 0) + 1;
      hasConfidence = true;
    }
  }
  if (hasConfidence) {
    lines.push(
      `Reviewed: ${confidenceCounts.reviewed} | Observed: ${confidenceCounts.observed} | Inferred: ${confidenceCounts.inferred}`,
    );
    lines.push('');
  }

  // Overall status
  const overallStatus: CheckStatus =
    report.summary.failed > 0
      ? 'failed'
      : report.summary.passed > 0
        ? 'passed'
        : 'untested';
  lines.push(`**Overall:** ${icon(overallStatus)}`);
  lines.push('');

  // Assumptions
  if (report.assumptions && report.assumptions.length > 0) {
    lines.push('## Assumptions');
    lines.push('');
    lines.push('| Type | Status | Details |');
    lines.push('|------|--------|---------|');
    for (const a of report.assumptions) {
      const details = a.reason ?? a.description ?? '\u2014';
      lines.push(`| \`${a.type}\` | ${icon(a.status)} | ${details} |`);
    }
    lines.push('');
  }

  // Defaults
  if (report.defaults && report.defaults.length > 0) {
    lines.push('## Default Properties');
    lines.push('');
    lines.push('| Property | Status | Details |');
    lines.push('|----------|--------|---------|');
    for (const d of report.defaults) {
      const details = d.reason ?? d.details ?? '\u2014';
      lines.push(`| ${d.property} | ${icon(d.status)} | ${details} |`);
    }
    lines.push('');
  }

  // Pages
  if (report.pages.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## Pages');
    lines.push('');
    for (const page of report.pages) {
      lines.push(...renderPageSection(page));
    }
  }

  // Flows
  if (report.flows.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## Flows');
    lines.push('');
    for (const flow of report.flows) {
      lines.push(...renderFlowSection(flow));
    }
  }

  lines.push('---');
  lines.push('');
  lines.push(`_Generated by Specify validator · ${new Date().toISOString()}_`);
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Page section
// ---------------------------------------------------------------------------

function renderPageSection(page: PageResult): string[] {
  const lines: string[] = [];
  const visitedStatus: CheckStatus = page.visited ? 'passed' : 'untested';

  lines.push(`### Page: \`${page.pageId}\` — \`${page.path}\``);
  lines.push('');
  lines.push(`**Visited:** ${icon(visitedStatus)}`);
  lines.push('');

  // Requests
  if (page.requests.length > 0) {
    lines.push('#### Expected Requests');
    lines.push('');
    lines.push('| Method | Pattern | Status | Matched URL | HTTP Status | Confidence |');
    lines.push('|--------|---------|--------|-------------|-------------|------------|');
    for (const req of page.requests) {
      const matchedUrl = req.matchedUrl ? `\`${truncate(req.matchedUrl, 60)}\`` : '\u2014';
      const httpStatus = req.actualStatus !== undefined ? String(req.actualStatus) : '\u2014';
      const conf = req.confidence ? `\`${req.confidence}\`` : '\u2014';
      lines.push(
        `| \`${req.method}\` | \`${req.urlPattern}\` | ${icon(req.status)} | ${matchedUrl} | ${httpStatus} | ${conf} |`,
      );
    }
    lines.push('');

    // Failure details
    const failures = page.requests.filter((r) => r.status === 'failed');
    if (failures.length > 0) {
      lines.push('<details>');
      lines.push('<summary>Request failure details</summary>');
      lines.push('');
      for (const req of failures) {
        lines.push(`**${req.method} ${req.urlPattern}**`);
        if (req.description) lines.push(`> ${req.description}`);
        if (req.confidence) lines.push(`> Confidence: ${req.confidence}`);
        if (req.reason) lines.push(`> Reason: ${req.reason}`);
        if (req.bodySchemaErrors?.length) {
          lines.push('> Schema errors:');
          for (const e of req.bodySchemaErrors) {
            lines.push(`>   - ${e}`);
          }
        }
        lines.push('');
      }
      lines.push('</details>');
      lines.push('');
    }
  }

  // Console expectations
  if (page.consoleExpectations.length > 0) {
    lines.push('#### Console Expectations');
    lines.push('');
    lines.push('| Level | Expected Count | Actual Count | Status |');
    lines.push('|-------|----------------|--------------|--------|');
    for (const ce of page.consoleExpectations) {
      const expected = ce.expectedCount !== undefined ? String(ce.expectedCount) : '—';
      const actual = ce.actualCount !== undefined ? String(ce.actualCount) : '—';
      lines.push(`| \`${ce.level}\` | ${expected} | ${actual} | ${icon(ce.status)} |`);
    }
    lines.push('');

    const consoleFailures = page.consoleExpectations.filter((c) => c.status === 'failed');
    if (consoleFailures.length > 0) {
      lines.push('<details>');
      lines.push('<summary>Console failure details</summary>');
      lines.push('');
      for (const ce of consoleFailures) {
        lines.push(`**console.${ce.level}**`);
        if (ce.reason) lines.push(`> ${ce.reason}`);
        if (ce.matchingEntries?.length) {
          lines.push('> Entries:');
          for (const entry of ce.matchingEntries.slice(0, 5)) {
            lines.push(`>   - \`${truncate(entry, 100)}\``);
          }
        }
        lines.push('');
      }
      lines.push('</details>');
      lines.push('');
    }
  }

  // Visual assertions
  if (page.visualAssertions.length > 0) {
    lines.push('#### Visual Assertions');
    lines.push('');
    lines.push('| Type | Selector | Status | Note |');
    lines.push('|------|----------|--------|------|');
    for (const va of page.visualAssertions) {
      const selector = va.selector ? `\`${va.selector}\`` : '—';
      const note = va.reason ? truncate(va.reason, 60) : '—';
      lines.push(`| \`${va.type}\` | ${selector} | ${icon(va.status)} | ${note} |`);
    }
    lines.push('');
  }

  // Scenarios
  if (page.scenarios.length > 0) {
    lines.push('#### Scenarios');
    lines.push('');
    for (const sc of page.scenarios) {
      lines.push(...renderScenarioSection(sc));
    }
  }

  return lines;
}

function renderScenarioSection(sc: ScenarioResult): string[] {
  const lines: string[] = [];
  lines.push(`##### Scenario: \`${sc.scenarioId}\` ${icon(sc.status)}`);
  if (sc.description) lines.push(`> ${sc.description}`);
  lines.push('');

  if (sc.steps.length > 0) {
    lines.push('| Step | Action | Status | Evidence |');
    lines.push('|------|--------|--------|----------|');
    sc.steps.forEach((step, i) => {
      const evidence = step.evidence ?? step.reason ?? '—';
      lines.push(
        `| ${i + 1} | \`${step.action}\` | ${icon(step.status)} | ${truncate(evidence, 60)} |`,
      );
    });
    lines.push('');
  }

  return lines;
}

// ---------------------------------------------------------------------------
// Flow section
// ---------------------------------------------------------------------------

function renderFlowSection(flow: FlowResult): string[] {
  const lines: string[] = [];
  lines.push(`### Flow: \`${flow.flowId}\` ${icon(flow.status)}`);
  if (flow.description) {
    lines.push(`> ${flow.description}`);
  }
  lines.push('');

  if (flow.steps.length > 0) {
    lines.push('| Step | Type | Status | Details |');
    lines.push('|------|------|--------|---------|');
    flow.steps.forEach((step, i) => {
      const details = renderFlowStepDetail(step);
      lines.push(`| ${i + 1} | \`${step.type}\` | ${icon(step.status)} | ${details} |`);
    });
    lines.push('');

    const failures = flow.steps.filter((s) => s.status === 'failed');
    if (failures.length > 0) {
      lines.push('<details>');
      lines.push('<summary>Flow failure details</summary>');
      lines.push('');
      for (const step of failures) {
        if (step.reason) lines.push(`> ${step.reason}`);
      }
      lines.push('</details>');
      lines.push('');
    }
  }

  return lines;
}

function renderFlowStepDetail(step: FlowStepResult): string {
  if (step.path) return `navigate → \`${step.path}\``;
  if (step.pageId) return `assert page: \`${step.pageId}\``;
  if (step.evidence) return truncate(step.evidence, 60);
  if (step.reason) return truncate(step.reason, 60);
  return step.description ?? '—';
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function truncate(str: string, maxLen: number): string {
  if (str.length <= maxLen) return str;
  return str.slice(0, maxLen - 3) + '...';
}

/** Collect all result objects that may carry a confidence field. */
function collectAllResults(
  report: GapReport,
): Array<{ confidence?: string }> {
  const results: Array<{ confidence?: string }> = [];
  for (const page of report.pages) {
    for (const req of page.requests) results.push(req);
    for (const va of page.visualAssertions) results.push(va);
    for (const ce of page.consoleExpectations) results.push(ce);
  }
  return results;
}
