/** Assets ship inside the CLI build; no CDN, frontend install, or second authoring format. */
export function viewerHtml(): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Specify · Spec browser</title><style>
:root{color-scheme:light;--ink:#172d45;--muted:#53677b;--line:#d6e0e9;--blue:#245ac4;--pale:#eaf1ff;--paper:#fff;--ground:#f3f6fa;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--ink);background:var(--ground)}
*{box-sizing:border-box}body{margin:0}button,input,select{font:inherit}button,a,input,select{outline-offset:4px}button{cursor:pointer}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid var(--blue)}
header{height:76px;display:flex;align-items:center;gap:24px;padding:12px 24px;border-bottom:1px solid var(--line);background:var(--paper)}.brand{font-weight:750;letter-spacing:-.04em;font-size:24px}.brand span{color:var(--blue)}#name{font-size:14px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.status{margin-left:auto;font-size:12px;color:var(--muted);white-space:nowrap}
#error{background:#fff0e9;color:#8a3217;padding:12px 24px;border-bottom:1px solid #e9bfa9;white-space:pre-wrap;overflow-wrap:anywhere}#error[hidden]{display:none}.shell{display:grid;grid-template-columns:220px 340px minmax(0,1fr);height:calc(100dvh - 76px)}aside,.catalog,.reader{overflow:auto;min-width:0}aside{padding:24px 12px;border-right:1px solid var(--line)}.label{font-size:11px;letter-spacing:.11em;text-transform:uppercase;color:var(--muted);font-weight:700;margin:0 12px 16px}
.area{border:0;background:transparent;color:var(--ink);display:flex;width:100%;text-align:left;align-items:center;justify-content:space-between;gap:12px;border-radius:6px;padding:10px 12px;margin:3px 0;font-size:13px;overflow-wrap:anywhere}.area[aria-current=true]{background:var(--pale);color:#194aab;font-weight:650}.area:hover{background:#e5ebf3}.count{font:11px ui-monospace,SFMono-Regular,Consolas,monospace;color:var(--muted);flex-shrink:0}.catalog{background:#fbfcfe;border-right:1px solid var(--line);display:flex;flex-direction:column}.searchbox{padding:20px 16px 14px;border-bottom:1px solid var(--line)}label{display:block;font-size:12px;font-weight:600;margin-bottom:8px}input,select{width:100%;padding:10px 12px;border:1px solid #a8b9ca;border-radius:6px;background:white;color:var(--ink)}#results-note{font-size:12px;color:var(--muted);margin:10px 0 0}#list{overflow:auto;flex:1;padding:8px}a.behavior{display:block;text-decoration:none;color:var(--ink);padding:14px 12px;border:1px solid transparent;border-radius:6px;margin:2px 0;font-size:13px;line-height:1.55}a.behavior:hover{background:#edf1f7}a.behavior[aria-current=true]{background:var(--paper);border-color:#b8cbed;box-shadow:inset 3px 0 var(--blue)}.behavior code{display:block;font-size:10px;color:var(--blue);margin-bottom:5px;overflow-wrap:anywhere}.summary{display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.pager{display:flex;align-items:center;justify-content:space-between;padding:12px 16px;border-top:1px solid var(--line);font-size:12px;gap:8px}button.small{background:white;border:1px solid var(--line);padding:7px 10px;border-radius:5px;color:var(--ink)}button:disabled{opacity:.4;cursor:default}
.reader{padding:40px clamp(24px,4vw,64px);background:var(--paper)}article{max-width:820px;margin:auto}h1{font-size:clamp(23px,2.2vw,32px);line-height:1.35;letter-spacing:-.025em;font-weight:650;margin:16px 0 24px}h2{font-size:13px;color:var(--muted);margin:32px 0 12px}p,.prose{line-height:1.75;font-size:15px;white-space:pre-wrap;overflow-wrap:anywhere}code{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:12px;overflow-wrap:anywhere}.id{color:var(--blue)}blockquote{border-left:3px solid #7fa3e2;margin:12px 0;padding:12px 20px;background:#f4f7ff;white-space:pre-wrap;line-height:1.7;overflow-wrap:anywhere}.reference{font-size:12px;color:var(--muted)}.tag{display:inline-block;background:var(--ground);border-radius:4px;padding:4px 8px;margin:0 6px 6px 0;font-size:11px}.formal{border:1px solid var(--line);border-radius:8px;padding:16px;margin:10px 0}.formal p{font-size:13px;margin:8px 0}.notice{font-size:13px;color:var(--muted);border-top:1px solid var(--line);padding-top:16px}.empty{color:var(--muted);font-size:14px;line-height:1.7;padding:20px}.mobile-areas{display:none}.skip{position:absolute;left:-10000px}.skip:focus{left:16px;top:12px;background:white;padding:10px;z-index:2}
@media(max-width:1050px){.shell{grid-template-columns:180px 280px minmax(0,1fr)}.reader{padding:28px 24px}header{gap:16px}}
@media(max-width:760px){header{height:auto;min-height:76px;flex-wrap:wrap;padding:12px 16px;gap:6px 16px}#name{max-width:55vw}.status{width:100%;margin:0}.shell{display:block;height:auto}aside{display:none}.mobile-areas{display:block;margin-bottom:14px}.catalog{border-right:0}.searchbox{padding:16px}#list{max-height:30dvh;min-height:100px}.reader{overflow:visible;padding:28px 20px}.pager{padding:8px 16px}h1{font-size:23px}}
</style><script type="module" src="/client.js"></script></head>
<body><a class="skip" href="#reader">Skip to spec detail</a><header><div class="brand">specify<span>.</span></div><div id="name">Spec browser</div><div class="status" id="status" role="status">Loading spec…</div></header>
<div id="error" role="alert" hidden></div><div class="shell">
<aside aria-label="Spec areas"><p class="label">Browse areas</p><nav id="areas"></nav></aside>
<section class="catalog" aria-label="Behavior browser"><div class="searchbox"><div class="mobile-areas"><label for="area-select">Area</label><select id="area-select"></select></div><label for="search">Search behaviors</label><input id="search" type="search" placeholder="ID, intent, source, tag, property…"><p id="results-note" role="status"></p></div><div id="list"></div><div class="pager"><button class="small" id="previous">Previous</button><span id="page"></span><button class="small" id="next">Next</button></div></section>
<main class="reader" id="reader" tabindex="-1"><article id="detail"><h1>Your spec, in view.</h1><p>Loading the current project spec…</p><noscript>Enable JavaScript to browse this local spec.</noscript></article></main></div></body></html>`;
}
